// This file was auto-generated by Fern from our API Definition.

package client

import (
	"encoding/json"
	"time"
)

// Common metadata for pagination
type MetaResponse struct {
	Page       int `json:"page"`
	Limit      int `json:"limit"`
	TotalItems int `json:"totalItems"`
	TotalPages int `json:"totalPages"`
}

// HealthResponse represents the health status of the API
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version,omitempty"`
}

// Project represents a Langfuse project
type Project struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Projects represents a list of projects
type Projects struct {
	Data []Project `json:"data"`
}

// Trace represents a trace in Langfuse
type Trace struct {
	ID            string                 `json:"id"`
	Name          *string                `json:"name,omitempty"`
	UserID        *string                `json:"userId,omitempty"`
	SessionID     *string                `json:"sessionId,omitempty"`
	Release       *string                `json:"release,omitempty"`
	Version       *string                `json:"version,omitempty"`
	Metadata      map[string]interface{} `json:"metadata,omitempty"`
	Tags          []string               `json:"tags,omitempty"`
	Input         interface{}            `json:"input,omitempty"`
	Output        interface{}            `json:"output,omitempty"`
	Timestamp     time.Time              `json:"timestamp"`
	CreatedAt     time.Time              `json:"createdAt"`
	UpdatedAt     time.Time              `json:"updatedAt"`
	Public        *bool                  `json:"public,omitempty"`
	ProjectID     string                 `json:"projectId"`
}

// CreateTraceBody represents the request body for creating a trace
type CreateTraceBody struct {
	ID        *string                `json:"id,omitempty"`
	Name      *string                `json:"name,omitempty"`
	UserID    *string                `json:"userId,omitempty"`
	SessionID *string                `json:"sessionId,omitempty"`
	Release   *string                `json:"release,omitempty"`
	Version   *string                `json:"version,omitempty"`
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
	Tags      []string               `json:"tags,omitempty"`
	Input     interface{}            `json:"input,omitempty"`
	Output    interface{}            `json:"output,omitempty"`
	Timestamp *time.Time             `json:"timestamp,omitempty"`
	Public    *bool                  `json:"public,omitempty"`
}

// UpdateTraceBody represents the request body for updating a trace
type UpdateTraceBody struct {
	Name      *string                `json:"name,omitempty"`
	UserID    *string                `json:"userId,omitempty"`
	SessionID *string                `json:"sessionId,omitempty"`
	Release   *string                `json:"release,omitempty"`
	Version   *string                `json:"version,omitempty"`
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
	Tags      []string               `json:"tags,omitempty"`
	Input     interface{}            `json:"input,omitempty"`
	Output    interface{}            `json:"output,omitempty"`
	Public    *bool                  `json:"public,omitempty"`
}

// Observation represents an observation (event, span, or generation)
type Observation struct {
	ID                string                 `json:"id"`
	TraceID           *string                `json:"traceId,omitempty"`
	ParentObservationID *string              `json:"parentObservationId,omitempty"`
	Type              ObservationType        `json:"type"`
	Name              *string                `json:"name,omitempty"`
	StartTime         time.Time              `json:"startTime"`
	EndTime           *time.Time             `json:"endTime,omitempty"`
	CompletionStartTime *time.Time           `json:"completionStartTime,omitempty"`
	Model             *string                `json:"model,omitempty"`
	ModelParameters   map[string]interface{} `json:"modelParameters,omitempty"`
	Input             interface{}            `json:"input,omitempty"`
	Output            interface{}            `json:"output,omitempty"`
	Metadata          map[string]interface{} `json:"metadata,omitempty"`
	Level             *ObservationLevel      `json:"level,omitempty"`
	StatusMessage     *string                `json:"statusMessage,omitempty"`
	Version           *string                `json:"version,omitempty"`
	Usage             *Usage                 `json:"usage,omitempty"`
	PromptTokens      *int                   `json:"promptTokens,omitempty"`
	CompletionTokens  *int                   `json:"completionTokens,omitempty"`
	TotalTokens       *int                   `json:"totalTokens,omitempty"`
	CreatedAt         time.Time              `json:"createdAt"`
	UpdatedAt         time.Time              `json:"updatedAt"`
}

// Usage represents token usage information
type Usage struct {
	PromptTokens     *int    `json:"promptTokens,omitempty"`
	CompletionTokens *int    `json:"completionTokens,omitempty"`
	TotalTokens      *int    `json:"totalTokens,omitempty"`
	Unit             *string `json:"unit,omitempty"`
	Input            *int    `json:"input,omitempty"`
	Output           *int    `json:"output,omitempty"`
	Total            *int    `json:"total,omitempty"`
	InputCost        *float64 `json:"inputCost,omitempty"`
	OutputCost       *float64 `json:"outputCost,omitempty"`
	TotalCost        *float64 `json:"totalCost,omitempty"`
}

// OpenAIUsage represents OpenAI-specific usage information
type OpenAIUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// CreateEventBody represents the request body for creating an event
type CreateEventBody struct {
	ID                  *string                `json:"id,omitempty"`
	TraceID             *string                `json:"traceId,omitempty"`
	ParentObservationID *string                `json:"parentObservationId,omitempty"`
	Name                *string                `json:"name,omitempty"`
	StartTime           *time.Time             `json:"startTime,omitempty"`
	Metadata            map[string]interface{} `json:"metadata,omitempty"`
	Input               interface{}            `json:"input,omitempty"`
	Output              interface{}            `json:"output,omitempty"`
	Level               *ObservationLevel      `json:"level,omitempty"`
	StatusMessage       *string                `json:"statusMessage,omitempty"`
	Version             *string                `json:"version,omitempty"`
}

// CreateSpanBody represents the request body for creating a span
type CreateSpanBody struct {
	ID                  *string                `json:"id,omitempty"`
	TraceID             *string                `json:"traceId,omitempty"`
	ParentObservationID *string                `json:"parentObservationId,omitempty"`
	Name                *string                `json:"name,omitempty"`
	StartTime           *time.Time             `json:"startTime,omitempty"`
	EndTime             *time.Time             `json:"endTime,omitempty"`
	Metadata            map[string]interface{} `json:"metadata,omitempty"`
	Input               interface{}            `json:"input,omitempty"`
	Output              interface{}            `json:"output,omitempty"`
	Level               *ObservationLevel      `json:"level,omitempty"`
	StatusMessage       *string                `json:"statusMessage,omitempty"`
	Version             *string                `json:"version,omitempty"`
}

// CreateGenerationBody represents the request body for creating a generation
type CreateGenerationBody struct {
	ID                  *string                `json:"id,omitempty"`
	TraceID             *string                `json:"traceId,omitempty"`
	ParentObservationID *string                `json:"parentObservationId,omitempty"`
	Name                *string                `json:"name,omitempty"`
	StartTime           *time.Time             `json:"startTime,omitempty"`
	EndTime             *time.Time             `json:"endTime,omitempty"`
	CompletionStartTime *time.Time             `json:"completionStartTime,omitempty"`
	Model               *string                `json:"model,omitempty"`
	ModelParameters     map[string]interface{} `json:"modelParameters,omitempty"`
	Metadata            map[string]interface{} `json:"metadata,omitempty"`
	Input               interface{}            `json:"input,omitempty"`
	Output              interface{}            `json:"output,omitempty"`
	Usage               *Usage                 `json:"usage,omitempty"`
	PromptName          *string                `json:"promptName,omitempty"`
	PromptVersion       *int                   `json:"promptVersion,omitempty"`
	Level               *ObservationLevel      `json:"level,omitempty"`
	StatusMessage       *string                `json:"statusMessage,omitempty"`
	Version             *string                `json:"version,omitempty"`
}

// UpdateEventBody represents the request body for updating an event
type UpdateEventBody struct {
	Metadata      map[string]interface{} `json:"metadata,omitempty"`
	Input         interface{}            `json:"input,omitempty"`
	Output        interface{}            `json:"output,omitempty"`
	Level         *ObservationLevel      `json:"level,omitempty"`
	StatusMessage *string                `json:"statusMessage,omitempty"`
}

// UpdateSpanBody represents the request body for updating a span
type UpdateSpanBody struct {
	EndTime       *time.Time             `json:"endTime,omitempty"`
	Metadata      map[string]interface{} `json:"metadata,omitempty"`
	Input         interface{}            `json:"input,omitempty"`
	Output        interface{}            `json:"output,omitempty"`
	Level         *ObservationLevel      `json:"level,omitempty"`
	StatusMessage *string                `json:"statusMessage,omitempty"`
}

// UpdateGenerationBody represents the request body for updating a generation
type UpdateGenerationBody struct {
	EndTime             *time.Time             `json:"endTime,omitempty"`
	CompletionStartTime *time.Time             `json:"completionStartTime,omitempty"`
	Metadata            map[string]interface{} `json:"metadata,omitempty"`
	Input               interface{}            `json:"input,omitempty"`
	Output              interface{}            `json:"output,omitempty"`
	Usage               *Usage                 `json:"usage,omitempty"`
	Level               *ObservationLevel      `json:"level,omitempty"`
	StatusMessage       *string                `json:"statusMessage,omitempty"`
}

// Score represents a score for a trace or observation
type Score struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	Value          interface{}   `json:"value"`
	DataType       ScoreDataType `json:"dataType"`
	Source         ScoreSource   `json:"source"`
	Comment        *string       `json:"comment,omitempty"`
	TraceID        string        `json:"traceId"`
	ObservationID  *string       `json:"observationId,omitempty"`
	ConfigID       *string       `json:"configId,omitempty"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
	AuthorUserID   *string       `json:"authorUserId,omitempty"`
}

// CreateScoreRequest represents the request body for creating a score
type CreateScoreRequest struct {
	ID            *string       `json:"id,omitempty"`
	Name          string        `json:"name"`
	Value         interface{}   `json:"value"`
	DataType      *ScoreDataType `json:"dataType,omitempty"`
	Comment       *string       `json:"comment,omitempty"`
	TraceID       string        `json:"traceId"`
	ObservationID *string       `json:"observationId,omitempty"`
	ConfigID      *string       `json:"configId,omitempty"`
}

// CreateScoreResponse represents the response for creating a score
type CreateScoreResponse struct {
	ID string `json:"id"`
}

// GetScoresResponse represents the response for getting scores
type GetScoresResponse struct {
	Data []Score      `json:"data"`
	Meta MetaResponse `json:"meta"`
}

// ScoreConfig represents a score configuration
type ScoreConfig struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	DataType    ScoreDataType `json:"dataType"`
	Description *string       `json:"description,omitempty"`
	MinValue    *float64      `json:"minValue,omitempty"`
	MaxValue    *float64      `json:"maxValue,omitempty"`
	Categories  []string      `json:"categories,omitempty"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

// Dataset represents a dataset
type Dataset struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description *string        `json:"description,omitempty"`
	Metadata    map[string]interface{} `json:"metadata,omitempty"`
	Status      *DatasetStatus `json:"status,omitempty"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	ProjectID   string         `json:"projectId"`
}

// CreateDatasetRequest represents the request body for creating a dataset
type CreateDatasetRequest struct {
	Name        string                 `json:"name"`
	Description *string                `json:"description,omitempty"`
	Metadata    map[string]interface{} `json:"metadata,omitempty"`
}

// PaginatedDatasets represents a paginated list of datasets
type PaginatedDatasets struct {
	Data []Dataset    `json:"data"`
	Meta MetaResponse `json:"meta"`
}

// DatasetItem represents an item in a dataset
type DatasetItem struct {
	ID                 string                 `json:"id"`
	DatasetID          string                 `json:"datasetId"`
	DatasetName        string                 `json:"datasetName"`
	Input              interface{}            `json:"input"`
	ExpectedOutput     interface{}            `json:"expectedOutput,omitempty"`
	Metadata           map[string]interface{} `json:"metadata,omitempty"`
	SourceTraceID      *string                `json:"sourceTraceId,omitempty"`
	SourceObservationID *string               `json:"sourceObservationId,omitempty"`
	Status             string                 `json:"status"`
	CreatedAt          time.Time              `json:"createdAt"`
	UpdatedAt          time.Time              `json:"updatedAt"`
}

// CreateDatasetItemRequest represents the request body for creating a dataset item
type CreateDatasetItemRequest struct {
	DatasetName         *string                `json:"datasetName,omitempty"`
	Input               interface{}            `json:"input"`
	ExpectedOutput      interface{}            `json:"expectedOutput,omitempty"`
	Metadata            map[string]interface{} `json:"metadata,omitempty"`
	SourceTraceID       *string                `json:"sourceTraceId,omitempty"`
	SourceObservationID *string                `json:"sourceObservationId,omitempty"`
}

// PaginatedDatasetItems represents a paginated list of dataset items
type PaginatedDatasetItems struct {
	Data []DatasetItem `json:"data"`
	Meta MetaResponse  `json:"meta"`
}

// DatasetRun represents a run of a dataset
type DatasetRun struct {
	ID          string                 `json:"id"`
	Name        string                 `json:"name"`
	Description *string                `json:"description,omitempty"`
	Metadata    map[string]interface{} `json:"metadata,omitempty"`
	DatasetID   string                 `json:"datasetId"`
	DatasetName string                 `json:"datasetName"`
	CreatedAt   time.Time              `json:"createdAt"`
	UpdatedAt   time.Time              `json:"updatedAt"`
}

// CreateDatasetRunRequest represents the request body for creating a dataset run
type CreateDatasetRunRequest struct {
	Name        string                 `json:"name"`
	Description *string                `json:"description,omitempty"`
	Metadata    map[string]interface{} `json:"metadata,omitempty"`
	DatasetID   string                 `json:"datasetId"`
}

// PaginatedDatasetRuns represents a paginated list of dataset runs
type PaginatedDatasetRuns struct {
	Data []DatasetRun `json:"data"`
	Meta MetaResponse `json:"meta"`
}

// DatasetRunItem represents an item in a dataset run
type DatasetRunItem struct {
	ID             string                 `json:"id"`
	DatasetRunID   string                 `json:"datasetRunId"`
	DatasetRunName string                 `json:"datasetRunName"`
	DatasetItemID  string                 `json:"datasetItemId"`
	TraceID        string                 `json:"traceId"`
	ObservationID  *string                `json:"observationId,omitempty"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt      time.Time              `json:"createdAt"`
	UpdatedAt      time.Time              `json:"updatedAt"`
}

// CreateDatasetRunItemRequest represents the request body for creating a dataset run item
type CreateDatasetRunItemRequest struct {
	RunName       string                 `json:"runName"`
	RunDescription *string               `json:"runDescription,omitempty"`
	RunMetadata   map[string]interface{} `json:"runMetadata,omitempty"`
	DatasetItemID string                 `json:"datasetItemId"`
	TraceID       string                 `json:"traceId"`
	ObservationID *string                `json:"observationId,omitempty"`
	Metadata      map[string]interface{} `json:"metadata,omitempty"`
}

// Session represents a session
type Session struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	ProjectID string    `json:"projectId"`
}

// SessionWithTraces represents a session with its traces
type SessionWithTraces struct {
	Session
	Traces []Trace `json:"traces"`
}

// PaginatedSessions represents a paginated list of sessions
type PaginatedSessions struct {
	Data []Session    `json:"data"`
	Meta MetaResponse `json:"meta"`
}

// Model represents a model configuration
type Model struct {
	ID                string          `json:"id"`
	ModelName         string          `json:"modelName"`
	MatchPattern      string          `json:"matchPattern"`
	StartDate         *time.Time      `json:"startDate,omitempty"`
	InputPrice        *float64        `json:"inputPrice,omitempty"`
	OutputPrice       *float64        `json:"outputPrice,omitempty"`
	TotalPrice        *float64        `json:"totalPrice,omitempty"`
	Unit              *ModelUsageUnit `json:"unit,omitempty"`
	TokenizerID       *string         `json:"tokenizerId,omitempty"`
	TokenizerConfig   map[string]interface{} `json:"tokenizerConfig,omitempty"`
	CreatedAt         time.Time       `json:"createdAt"`
	UpdatedAt         time.Time       `json:"updatedAt"`
}

// CreateModelRequest represents the request body for creating a model
type CreateModelRequest struct {
	ModelName       string          `json:"modelName"`
	MatchPattern    string          `json:"matchPattern"`
	StartDate       *time.Time      `json:"startDate,omitempty"`
	InputPrice      *float64        `json:"inputPrice,omitempty"`
	OutputPrice     *float64        `json:"outputPrice,omitempty"`
	TotalPrice      *float64        `json:"totalPrice,omitempty"`
	Unit            *ModelUsageUnit `json:"unit,omitempty"`
	TokenizerID     *string         `json:"tokenizerId,omitempty"`
	TokenizerConfig map[string]interface{} `json:"tokenizerConfig,omitempty"`
}

// PaginatedModels represents a paginated list of models
type PaginatedModels struct {
	Data []Model      `json:"data"`
	Meta MetaResponse `json:"meta"`
}

// Comment represents a comment on a trace or observation
type Comment struct {
	ID          string            `json:"id"`
	Content     string            `json:"content"`
	ObjectType  CommentObjectType `json:"objectType"`
	ObjectID    string            `json:"objectId"`
	ProjectID   string            `json:"projectId"`
	AuthorUserID string           `json:"authorUserId"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

// CreateCommentRequest represents the request body for creating a comment
type CreateCommentRequest struct {
	Content    string            `json:"content"`
	ObjectType CommentObjectType `json:"objectType"`
	ObjectID   string            `json:"objectId"`
}

// CreateCommentResponse represents the response for creating a comment
type CreateCommentResponse struct {
	ID string `json:"id"`
}

// GetCommentsResponse represents the response for getting comments
type GetCommentsResponse struct {
	Data []Comment    `json:"data"`
	Meta MetaResponse `json:"meta"`
}

// GetMediaResponse represents the response for getting media
type GetMediaResponse struct {
	MediaID     string           `json:"mediaId"`
	ContentType MediaContentType `json:"contentType"`
	ContentLength int            `json:"contentLength"`
	UploadedAt  time.Time        `json:"uploadedAt"`
}

// GetMediaUploadUrlRequest represents the request for getting a media upload URL
type GetMediaUploadUrlRequest struct {
	ContentType   MediaContentType `json:"contentType"`
	ContentLength int              `json:"contentLength"`
	TraceID       *string          `json:"traceId,omitempty"`
	ObservationID *string          `json:"observationId,omitempty"`
	Field         *string          `json:"field,omitempty"`
}

// GetMediaUploadUrlResponse represents the response for getting a media upload URL
type GetMediaUploadUrlResponse struct {
	MediaID   string `json:"mediaId"`
	UploadURL string `json:"uploadUrl"`
}

// PatchMediaBody represents the request body for patching media
type PatchMediaBody struct {
	TraceID       *string `json:"traceId,omitempty"`
	ObservationID *string `json:"observationId,omitempty"`
	Field         *string `json:"field,omitempty"`
}

// DailyMetrics represents daily metrics
type DailyMetrics struct {
	Date              string  `json:"date"`
	CountTraces       int     `json:"countTraces"`
	CountObservations int     `json:"countObservations"`
	TotalCost         float64 `json:"totalCost"`
	Usage             []Usage `json:"usage"`
}

// IngestionRequest represents a request to the ingestion API
type IngestionRequest struct {
	Batch     []interface{} `json:"batch"`
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
}

// IngestionResponse represents a response from the ingestion API
type IngestionResponse struct {
	Successes []string `json:"successes"`
	Errors    []struct {
		ID      string `json:"id"`
		Status  int    `json:"status"`
		Message string `json:"message"`
		Error   string `json:"error"`
	} `json:"errors"`
}

// ObservationsView represents an observation view
type ObservationsView struct {
	Data []Observation `json:"data"`
	Meta MetaResponse  `json:"meta"`
}

// Sort represents sorting parameters
type Sort struct {
	Column string `json:"column"`
	Order  string `json:"order"`
}

// AnnotationQueue represents an annotation queue
type AnnotationQueue struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description,omitempty"`
	ScoreConfigIDs []string  `json:"scoreConfigIds"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

// AnnotationQueueItem represents an item in an annotation queue
type AnnotationQueueItem struct {
	ID          string                    `json:"id"`
	QueueID     string                    `json:"queueId"`
	ObjectID    string                    `json:"objectId"`
	ObjectType  AnnotationQueueObjectType `json:"objectType"`
	Status      AnnotationQueueStatus     `json:"status"`
	CompletedAt *time.Time                `json:"completedAt,omitempty"`
	CreatedAt   time.Time                 `json:"createdAt"`
	UpdatedAt   time.Time                 `json:"updatedAt"`
}

// PaginatedAnnotationQueues represents a paginated list of annotation queues
type PaginatedAnnotationQueues struct {
	Data []AnnotationQueue `json:"data"`
	Meta MetaResponse      `json:"meta"`
}

// PaginatedAnnotationQueueItems represents a paginated list of annotation queue items
type PaginatedAnnotationQueueItems struct {
	Data []AnnotationQueueItem `json:"data"`
	Meta MetaResponse          `json:"meta"`
}

// CreateAnnotationQueueRequest represents the request body for creating an annotation queue
type CreateAnnotationQueueRequest struct {
	Name           string   `json:"name"`
	Description    *string  `json:"description,omitempty"`
	ScoreConfigIDs []string `json:"scoreConfigIds"`
}

// CreateAnnotationQueueItemRequest represents the request body for creating an annotation queue item
type CreateAnnotationQueueItemRequest struct {
	ObjectID   string                    `json:"objectId"`
	ObjectType AnnotationQueueObjectType `json:"objectType"`
	Status     *AnnotationQueueStatus    `json:"status,omitempty"`
}

// UpdateAnnotationQueueItemRequest represents the request body for updating an annotation queue item
type UpdateAnnotationQueueItemRequest struct {
	Status *AnnotationQueueStatus `json:"status,omitempty"`
}

// DeleteAnnotationQueueItemResponse represents the response for deleting an annotation queue item
type DeleteAnnotationQueueItemResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// CreateAnnotationQueueAssignmentResponse represents the response for creating an annotation queue assignment
type CreateAnnotationQueueAssignmentResponse struct {
	UserID    string `json:"userId"`
	QueueID   string `json:"queueId"`
	ProjectID string `json:"projectId"`
}

// AnnotationQueueAssignmentRequest represents the request body for creating an annotation queue assignment
type AnnotationQueueAssignmentRequest struct {
	UserID string `json:"userId"`
}

// DeleteAnnotationQueueAssignmentResponse represents the response for deleting an annotation queue assignment
type DeleteAnnotationQueueAssignmentResponse struct {
	Success bool `json:"success"`
}

// ChatMessage represents a chat message in a prompt
type ChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// ChatPrompt represents a chat-based prompt
type ChatPrompt struct {
	Name      string        `json:"name"`
	Version   int           `json:"version"`
	Config    interface{}   `json:"config,omitempty"`
	Prompt    []ChatMessage `json:"prompt"`
	Tags      []string      `json:"tags,omitempty"`
	Labels    []string      `json:"labels,omitempty"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
	CreatedBy string        `json:"createdBy"`
	Type      string        `json:"type"`
}

// TextPrompt represents a text-based prompt
type TextPrompt struct {
	Name      string      `json:"name"`
	Version   int         `json:"version"`
	Config    interface{} `json:"config,omitempty"`
	Prompt    string      `json:"prompt"`
	Tags      []string    `json:"tags,omitempty"`
	Labels    []string    `json:"labels,omitempty"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
	CreatedBy string      `json:"createdBy"`
	Type      string      `json:"type"`
}

// CreateChatPromptRequest represents the request body for creating a chat prompt
type CreateChatPromptRequest struct {
	Name      string        `json:"name"`
	Prompt    []ChatMessage `json:"prompt"`
	Config    interface{}   `json:"config,omitempty"`
	Tags      []string      `json:"tags,omitempty"`
	Labels    []string      `json:"labels,omitempty"`
}

// CreateTextPromptRequest represents the request body for creating a text prompt
type CreateTextPromptRequest struct {
	Name   string      `json:"name"`
	Prompt string      `json:"prompt"`
	Config interface{} `json:"config,omitempty"`
	Tags   []string    `json:"tags,omitempty"`
	Labels []string    `json:"labels,omitempty"`
}

// PromptMetaListResponse represents a list of prompt metadata
type PromptMetaListResponse struct {
	Data []struct {
		Name      string    `json:"name"`
		Version   int       `json:"version"`
		Type      string    `json:"type"`
		Tags      []string  `json:"tags"`
		Labels    []string  `json:"labels"`
		CreatedAt time.Time `json:"createdAt"`
		UpdatedAt time.Time `json:"updatedAt"`
	} `json:"data"`
	Meta MetaResponse `json:"meta"`
}

// FileParam represents a file parameter for multipart uploads
type FileParam struct {
	Reader      interface{} // io.Reader
	Filename    string
	ContentType string
}

// NewFileParam creates a new FileParam
func NewFileParam(reader interface{}, filename string, contentType string, opts ...interface{}) *FileParam {
	return &FileParam{
		Reader:      reader,
		Filename:    filename,
		ContentType: contentType,
	}
}

// Ensure all types implement json.Marshaler and json.Unmarshaler where needed
var (
	_ json.Marshaler = (*Trace)(nil)
	_ json.Marshaler = (*Observation)(nil)
	_ json.Marshaler = (*Score)(nil)
	_ json.Marshaler = (*Dataset)(nil)
)

// MarshalJSON implements json.Marshaler for types
func (t *Trace) MarshalJSON() ([]byte, error) {
	type Alias Trace
	return json.Marshal((*Alias)(t))
}

func (o *Observation) MarshalJSON() ([]byte, error) {
	type Alias Observation
	return json.Marshal((*Alias)(o))
}

func (s *Score) MarshalJSON() ([]byte, error) {
	type Alias Score
	return json.Marshal((*Alias)(s))
}

func (d *Dataset) MarshalJSON() ([]byte, error) {
	type Alias Dataset
	return json.Marshal((*Alias)(d))
}
