// This file was auto-generated by Fern from our API Definition.

package types

import (
	"encoding/json"
	"fmt"

	"github.com/bytedance/sonic"
)

// CommentObjectType represents the type of object a comment is attached to.
type CommentObjectType string

const (
	CommentObjectTypeTrace       CommentObjectType = "TRACE"
	CommentObjectTypeObservation CommentObjectType = "OBSERVATION"
	CommentObjectTypeSession     CommentObjectType = "SESSION"
)

func NewCommentObjectTypeFromString(s string) (CommentObjectType, error) {
	switch s {
	case "TRACE":
		return CommentObjectTypeTrace, nil
	case "OBSERVATION":
		return CommentObjectTypeObservation, nil
	case "SESSION":
		return CommentObjectTypeSession, nil
	}
	return "", fmt.Errorf("invalid CommentObjectType: %s", s)
}

// DatasetStatus represents the status of a dataset.
type DatasetStatus string

const (
	DatasetStatusActive   DatasetStatus = "ACTIVE"
	DatasetStatusArchived DatasetStatus = "ARCHIVED"
)

func NewDatasetStatusFromString(s string) (DatasetStatus, error) {
	switch s {
	case "ACTIVE":
		return DatasetStatusActive, nil
	case "ARCHIVED":
		return DatasetStatusArchived, nil
	}
	return "", fmt.Errorf("invalid DatasetStatus: %s", s)
}

// MediaContentType represents the content type of media.
type MediaContentType string

const (
	MediaContentTypeImagePng  MediaContentType = "image/png"
	MediaContentTypeImageJpeg MediaContentType = "image/jpeg"
	MediaContentTypeImageGif  MediaContentType = "image/gif"
	MediaContentTypeImageWebp MediaContentType = "image/webp"
	MediaContentTypeTextPlain MediaContentType = "text/plain"
	MediaContentTypeAudioMpeg MediaContentType = "audio/mpeg"
	MediaContentTypeAudioWav  MediaContentType = "audio/wav"
	MediaContentTypeVideoMp4  MediaContentType = "video/mp4"
)

func NewMediaContentTypeFromString(s string) (MediaContentType, error) {
	switch s {
	case "image/png":
		return MediaContentTypeImagePng, nil
	case "image/jpeg":
		return MediaContentTypeImageJpeg, nil
	case "image/gif":
		return MediaContentTypeImageGif, nil
	case "image/webp":
		return MediaContentTypeImageWebp, nil
	case "text/plain":
		return MediaContentTypeTextPlain, nil
	case "audio/mpeg":
		return MediaContentTypeAudioMpeg, nil
	case "audio/wav":
		return MediaContentTypeAudioWav, nil
	case "video/mp4":
		return MediaContentTypeVideoMp4, nil
	}
	return "", fmt.Errorf("invalid MediaContentType: %s", s)
}

// ModelUsageUnit represents the unit of model usage.
type ModelUsageUnit string

const (
	ModelUsageUnitCharacters      ModelUsageUnit = "CHARACTERS"
	ModelUsageUnitTokens          ModelUsageUnit = "TOKENS"
	ModelUsageUnitSeconds         ModelUsageUnit = "SECONDS"
	ModelUsageUnitMilliseconds    ModelUsageUnit = "MILLISECONDS"
	ModelUsageUnitImages          ModelUsageUnit = "IMAGES"
	ModelUsageUnitRequests        ModelUsageUnit = "REQUESTS"
)

func NewModelUsageUnitFromString(s string) (ModelUsageUnit, error) {
	switch s {
	case "CHARACTERS":
		return ModelUsageUnitCharacters, nil
	case "TOKENS":
		return ModelUsageUnitTokens, nil
	case "SECONDS":
		return ModelUsageUnitSeconds, nil
	case "MILLISECONDS":
		return ModelUsageUnitMilliseconds, nil
	case "IMAGES":
		return ModelUsageUnitImages, nil
	case "REQUESTS":
		return ModelUsageUnitRequests, nil
	}
	return "", fmt.Errorf("invalid ModelUsageUnit: %s", s)
}

// ObservationLevel represents the level of an observation.
type ObservationLevel string

const (
	ObservationLevelDebug   ObservationLevel = "DEBUG"
	ObservationLevelDefault ObservationLevel = "DEFAULT"
	ObservationLevelWarning ObservationLevel = "WARNING"
	ObservationLevelError   ObservationLevel = "ERROR"
)

func NewObservationLevelFromString(s string) (ObservationLevel, error) {
	switch s {
	case "DEBUG":
		return ObservationLevelDebug, nil
	case "DEFAULT":
		return ObservationLevelDefault, nil
	case "WARNING":
		return ObservationLevelWarning, nil
	case "ERROR":
		return ObservationLevelError, nil
	}
	return "", fmt.Errorf("invalid ObservationLevel: %s", s)
}

// ObservationType represents the type of observation.
type ObservationType string

const (
	ObservationTypeEvent      ObservationType = "EVENT"
	ObservationTypeSpan       ObservationType = "SPAN"
	ObservationTypeGeneration ObservationType = "GENERATION"
)

func NewObservationTypeFromString(s string) (ObservationType, error) {
	switch s {
	case "EVENT":
		return ObservationTypeEvent, nil
	case "SPAN":
		return ObservationTypeSpan, nil
	case "GENERATION":
		return ObservationTypeGeneration, nil
	}
	return "", fmt.Errorf("invalid ObservationType: %s", s)
}

// ScoreDataType represents the data type of a score.
type ScoreDataType string

const (
	ScoreDataTypeNumeric     ScoreDataType = "NUMERIC"
	ScoreDataTypeCategorical ScoreDataType = "CATEGORICAL"
	ScoreDataTypeBoolean     ScoreDataType = "BOOLEAN"
)

func NewScoreDataTypeFromString(s string) (ScoreDataType, error) {
	switch s {
	case "NUMERIC":
		return ScoreDataTypeNumeric, nil
	case "CATEGORICAL":
		return ScoreDataTypeCategorical, nil
	case "BOOLEAN":
		return ScoreDataTypeBoolean, nil
	}
	return "", fmt.Errorf("invalid ScoreDataType: %s", s)
}

// ScoreSource represents the source of a score.
type ScoreSource string

const (
	ScoreSourceAnnotation ScoreSource = "ANNOTATION"
	ScoreSourceAPI        ScoreSource = "API"
	ScoreSourceEval       ScoreSource = "EVAL"
)

func NewScoreSourceFromString(s string) (ScoreSource, error) {
	switch s {
	case "ANNOTATION":
		return ScoreSourceAnnotation, nil
	case "API":
		return ScoreSourceAPI, nil
	case "EVAL":
		return ScoreSourceEval, nil
	}
	return "", fmt.Errorf("invalid ScoreSource: %s", s)
}

// AnnotationQueueStatus represents the status of an annotation queue item.
type AnnotationQueueStatus string

const (
	AnnotationQueueStatusPending   AnnotationQueueStatus = "PENDING"
	AnnotationQueueStatusCompleted AnnotationQueueStatus = "COMPLETED"
)

func NewAnnotationQueueStatusFromString(s string) (AnnotationQueueStatus, error) {
	switch s {
	case "PENDING":
		return AnnotationQueueStatusPending, nil
	case "COMPLETED":
		return AnnotationQueueStatusCompleted, nil
	}
	return "", fmt.Errorf("invalid AnnotationQueueStatus: %s", s)
}

// AnnotationQueueObjectType represents the type of object in an annotation queue.
type AnnotationQueueObjectType string

const (
	AnnotationQueueObjectTypeTrace       AnnotationQueueObjectType = "TRACE"
	AnnotationQueueObjectTypeObservation AnnotationQueueObjectType = "OBSERVATION"
	AnnotationQueueObjectTypeSession     AnnotationQueueObjectType = "SESSION"
)

func NewAnnotationQueueObjectTypeFromString(s string) (AnnotationQueueObjectType, error) {
	switch s {
	case "TRACE":
		return AnnotationQueueObjectTypeTrace, nil
	case "OBSERVATION":
		return AnnotationQueueObjectTypeObservation, nil
	case "SESSION":
		return AnnotationQueueObjectTypeSession, nil
	}
	return "", fmt.Errorf("invalid AnnotationQueueObjectType: %s", s)
}

// Ensure enums implement json.Marshaler and json.Unmarshaler
var (
	_ json.Marshaler   = (*CommentObjectType)(nil)
	_ json.Unmarshaler = (*CommentObjectType)(nil)
	_ json.Marshaler   = (*DatasetStatus)(nil)
	_ json.Unmarshaler = (*DatasetStatus)(nil)
	_ json.Marshaler   = (*MediaContentType)(nil)
	_ json.Unmarshaler = (*MediaContentType)(nil)
	_ json.Marshaler   = (*ModelUsageUnit)(nil)
	_ json.Unmarshaler = (*ModelUsageUnit)(nil)
	_ json.Marshaler   = (*ObservationLevel)(nil)
	_ json.Unmarshaler = (*ObservationLevel)(nil)
	_ json.Marshaler   = (*ObservationType)(nil)
	_ json.Unmarshaler = (*ObservationType)(nil)
	_ json.Marshaler   = (*ScoreDataType)(nil)
	_ json.Unmarshaler = (*ScoreDataType)(nil)
	_ json.Marshaler   = (*ScoreSource)(nil)
	_ json.Unmarshaler = (*ScoreSource)(nil)
)

// MarshalJSON implements sonic.Marshaler
func (c CommentObjectType) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(c))
}

// UnmarshalJSON implements sonic.Unmarshaler
func (c *CommentObjectType) UnmarshalJSON(data []byte) error {
	var s string
	if err := sonic.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := NewCommentObjectTypeFromString(s)
	if err != nil {
		return err
	}
	*c = val
	return nil
}

// Similar implementations for other enums...
func (d DatasetStatus) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(d))
}

func (d *DatasetStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := sonic.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := NewDatasetStatusFromString(s)
	if err != nil {
		return err
	}
	*d = val
	return nil
}

func (m MediaContentType) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(m))
}

func (m *MediaContentType) UnmarshalJSON(data []byte) error {
	var s string
	if err := sonic.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := NewMediaContentTypeFromString(s)
	if err != nil {
		return err
	}
	*m = val
	return nil
}

func (m ModelUsageUnit) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(m))
}

func (m *ModelUsageUnit) UnmarshalJSON(data []byte) error {
	var s string
	if err := sonic.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := NewModelUsageUnitFromString(s)
	if err != nil {
		return err
	}
	*m = val
	return nil
}

func (o ObservationLevel) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(o))
}

func (o *ObservationLevel) UnmarshalJSON(data []byte) error {
	var s string
	if err := sonic.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := NewObservationLevelFromString(s)
	if err != nil {
		return err
	}
	*o = val
	return nil
}

func (o ObservationType) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(o))
}

func (o *ObservationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := sonic.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := NewObservationTypeFromString(s)
	if err != nil {
		return err
	}
	*o = val
	return nil
}

func (s ScoreDataType) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(s))
}

func (s *ScoreDataType) UnmarshalJSON(data []byte) error {
	var str string
	if err := sonic.Unmarshal(data, &str); err != nil {
		return err
	}
	val, err := NewScoreDataTypeFromString(str)
	if err != nil {
		return err
	}
	*s = val
	return nil
}

func (s ScoreSource) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(s))
}

func (s *ScoreSource) UnmarshalJSON(data []byte) error {
	var str string
	if err := sonic.Unmarshal(data, &str); err != nil {
		return err
	}
	val, err := NewScoreSourceFromString(str)
	if err != nil {
		return err
	}
	*s = val
	return nil
}

func (a AnnotationQueueStatus) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(a))
}

func (a *AnnotationQueueStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := sonic.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := NewAnnotationQueueStatusFromString(s)
	if err != nil {
		return err
	}
	*a = val
	return nil
}

func (a AnnotationQueueObjectType) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(string(a))
}

func (a *AnnotationQueueObjectType) UnmarshalJSON(data []byte) error {
	var s string
	if err := sonic.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := NewAnnotationQueueObjectTypeFromString(s)
	if err != nil {
		return err
	}
	*a = val
	return nil
}
